<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CmsLiveviewEditor\Block\Element;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfoHours;

/** @var ViewModelRegistry $viewModels */
/** @var Element $block */
/** @var Escaper $escaper */

/** @var StoreInfoHours $storeInfoHours */
$storeInfoHours = $viewModels->require(StoreInfoHours::class);

$classes = $block->getClasses() ?: 'storeinfo';

$headingTag = $block->getHeadingTag() ?? 'h2';
$headingText = $block->getHeading();
$headingClasses = implode(' ', array_filter([
    'mb-4',
    $block->getHeadingClasses() === "default" ? 'text-base leading-5 font-semibold tracking-wider uppercase' : '',
    $block->getHeadingClasses() === "large" ? 'text-2xl lg:text-4xl' : ''
]));

$showFullNameOfDay = $block->getShowFullNameOfDay() !== null ? $block->getShowFullNameOfDay() : true;
?>

<?php if ($storeInfoHours): ?>
    <div
        <?= $escaper->escapeHtmlAttr($block->renderBlockId()) ?>
        class="<?= $escaper->escapeHtmlAttr($classes) ?>"
        data-liveview-element="storeinfo-hours"
        <?= /** @noEscape */ $block->getEditorAttrs() ?>
    >
        <?php if($headingText): ?>
            <<?= $escaper->escapeHtmlAttr($headingTag) ?>
                class="<?= $escaper->escapeHtmlAttr($headingClasses) ?>"
            >
                <?= $escaper->escapeHtml($headingText); ?>
            </<?= $escaper->escapeHtmlAttr($headingTag) ?>>
        <?php endif; ?>
        <dl class="grid grid-cols-[auto_1fr] gap-y-1 gap-x-2">
            <?php foreach ($storeInfoHours->getOpeningHours() as $day): ?>
                <dt class="font-semibold"><?= $escaper->escapeHtmlAttr(
                    $storeInfoHours->getFullNameOfDay($day['day'])
                ); ?></dt>
                <dd><?= $escaper->escapeHtmlAttr($day['hours']); ?></dd>
            <?php endforeach; ?>
        </dl>
    </div>
<?php else: ?>
    <?= /** @noEscape */ $block->renderEditorMessage(['preview_message' => __('No Store Hours Configured')]) ?>
<?php endif; ?>
