<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfoHours;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreInfoHours $storeInfoHours */

$storeInfoHours = $block->getData('viewModelStoreInfo');;

if (!$storeInfoHours->enabled()) {
    return '';
}
?>

<div class="storehours footer-block">
    <dl>
        <?php foreach ($storeInfoHours->getOpeningHours() as $day): ?>
            <dt><?= $day['day']; ?></dt>
            <dd><?= $day['hours']; ?></dd>
        <?php endforeach; ?>
    </dl>
</div>
