<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfo;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfo $storeInfo */
$storeInfo = $viewModels->require(StoreInfo::class);

$storeNameFallback = parse_url($block->getBaseUrl())['host'];

$classList = $block->getClassList() !== null ? $block->getClassList() : 'pr-4 lg:w-1/4 md:w-1/2 space-y-4';
?>

<div
    class="storeinfo <?= $escaper->escapeHtmlAttr($classList) ?>"
    itemscope
    itemtype="https://schema.org/Store"
>
    <div
        class="mb-4 text-md leading-5 tracking-wider uppercase"
        itemprop="name"
    >
        <strong class="font-semibold"><?= $escaper->escapeHtml($storeInfo->getStoreName() ?: $storeNameFallback); ?></strong>
    </div>
    <address
        class="not-italic"
        itemprop="address"
        itemscope
        itemtype="https://schema.org/PostalAddress"
    >
        <?php if ($address1 = $storeInfo->getStreetLine1()): ?>
            <span itemprop="streetAddress">
                <?= $escaper->escapeHtml($address1); ?>
                <?php if ($address2 = $storeInfo->getStreetLine2()): ?>
                    <?= $escaper->escapeHtml($address2); ?>
                <?php endif; ?>
            </span>
            <br>
        <?php endif; ?>
        <?php if ($postcode = $storeInfo->getPostcode()): ?>
            <span itemprop="postalCode"><?= $escaper->escapeHtml($postcode); ?></span>
        <?php endif; ?>
        <?php if ($city = $storeInfo->getCity()): ?>
            <span itemprop="addressLocality"><?= $escaper->escapeHtml($city); ?></span>
            <br>
        <?php endif; ?>
        <?php if ($country = $storeInfo->getCountry()): ?>
            <?php if ($region = $storeInfo->getRegion()): ?>
                <span itemprop="addressRegion"><?= $escaper->escapeHtml($region); ?>,</span>
            <?php endif; ?>
            <span itemprop="addressCountry"><?= $escaper->escapeHtml($country); ?></span>
        <?php endif; ?>
    </address>
    <dl class="grid grid-cols-[auto_1fr] gap-y-1 gap-x-2">
        <?php if ($hours = $storeInfo->getHours()): ?>
            <dt class="text-slate-600 text-sm"><?= $escaper->escapeHtml(__('Opening Hours')) ?>:</dt>
            <dd><?= $escaper->escapeHtml($hours); ?></dd>
        <?php endif; ?>
        <?php if ($phone = $storeInfo->getPhone()): ?>
            <dt class="text-slate-600 text-sm"><?= $escaper->escapeHtml(__('Phone')) ?>:</dt>
            <dd itemprop="telephone">
                <a href="tel:<?= $escaper->escapeHtmlAttr($storeInfo->formatPhoneNumber($phone)) ?>">
                    <?= $escaper->escapeHtml($phone); ?>
                </a>
            </dd>
            <?php if ($extraPhone = $storeInfo->getExtraPhone()): ?>
                <dd class="col-start-2">
                    <a href="tel:<?= $escaper->escapeHtmlAttr($storeInfo->formatPhoneNumber($extraPhone)) ?>">
                        <?= $escaper->escapeHtml($extraPhone); ?>
                    </a>
                </dd>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($phone = $storeInfo->getWhatsApp()): ?>
            <dt class="text-slate-600 text-sm"><?= $escaper->escapeHtml(__('Whatsapp')) ?>:</dt>
            <dd>
                <a href="tel:<?= $escaper->escapeHtmlAttr($storeInfo->formatPhoneNumber($phone)) ?>">
                    <?= $escaper->escapeHtml($phone); ?>
                </a>
            </dd>
        <?php endif; ?>
        <?php if ($email = $storeInfo->getEmail()): ?>
            <dt class="text-slate-600 text-sm"><?= $escaper->escapeHtml(__('Email')) ?>:</dt>
            <dd itemprop="email">
                <a href="mailto:<?= $escaper->escapeHtml($email); ?>" class="hyphens-auto">
                    <?= $escaper->escapeHtml($email); ?>
                </a>
            </dd>
        <?php endif; ?>
        <?php if ($vat_number = $storeInfo->getVatNumber()): ?>
            <dt class="text-slate-600 text-sm"><?= $escaper->escapeHtml(__('VAT-Number')) ?>:</dt>
            <dd><?= $escaper->escapeHtml($vat_number); ?></dd>
        <?php endif; ?>
        <?php if ($coc_number = $storeInfo->getCocNumber()): ?>
            <dt class="text-slate-600 text-sm"><?= $escaper->escapeHtml(__('CoC-Number')) ?>:</dt>
            <dd><?= $escaper->escapeHtml($coc_number); ?></dd>
        <?php endif; ?>
    </dl>
</div>
