<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfoHours;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreInfoHours $storeInfoHours */

$storeInfoHours = $viewModels->require(StoreInfoHours::class);

if (!$storeInfoHours->enabled()) {
    return '';
}
?>

<div class="storehours pr-4 lg:w-1/4 md:w-1/2 space-y-4">
    <dl class="grid grid-cols-[auto_1fr] gap-y-1 gap-x-2">
        <?php foreach ($storeInfoHours->getOpeningHours() as $day): ?>
            <dt class="font-semibold"><?= $day['day']; ?></dt>
            <dd><?= $day['hours']; ?></dd>
        <?php endforeach; ?>
    </dl>
</div>
