<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfoSocials;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreInfoSocials $socials */

$socials = $viewModels->require(StoreInfoSocials::class);

$socialsList = [];

if ($socials->getLinkedIn()) {
    array_push($socialsList, [
        'type' => 'linkedin',
        'link' => $socials->getLinkedIn(),
        'title' => __('Go to our %1 page', 'LinkedIn')
    ]);
}

if ($socials->getFacebook()) {
    array_push($socialsList, [
        'type' => 'facebook',
        'link' => $socials->getFacebook(),
        'title' => __('Go to our %1 page', 'Facebook')
    ]);
}

if ($socials->getInstagram()) {
    array_push($socialsList, [
        'type' => 'instagram',
        'link' => $socials->getInstagram()
            ? 'https://www.instagram.com/' . $socials->getInstagram()
            : '',
        'title' => __('Explore our %1 page', 'Instagram')
    ]);
}

if ($socials->getBluesky()) {
    array_push($socialsList, [
        'type' => 'bluesky',
        'link' => $socials->getBluesky(),
        'title' => __('Explore our %1 page', 'Bluesky')
    ]);
}

if ($socials->getMastodon()) {
    array_push($socialsList, [
        'type' => 'mastodon',
        'link' => $socials->getMastodon(),
        'title' => __('Explore our %1 page', 'Mastodon')
    ]);
}

if ($socials->getTwitter()) {
    array_push($socialsList, [
        'type' => 'twitter',
        'link' => $socials->getTwitter()
            ? 'https://twitter.com/' . $socials->getTwitter()
            : '',
        'title' => __('Visit %1 on Twitter for more', $socials->getTwitter())
    ]);
}

if ($socials->getPinterest()) {
    array_push($socialsList, [
        'type' => 'pinterest',
        'link' => $socials->getPinterest(),
        'title' => __('Explore our %1 page', 'Pinterest')
    ]);
}

if ($socials->getYouTube()) {
    array_push($socialsList, [
        'type' => 'youtube',
        'link' => $socials->getYouTube(),
        'title' => __('Go to our %1 page', 'YouTube')
    ]);
}

if ($socials->getVimeo()) {
    array_push($socialsList, [
        'type' => 'vimeo',
        'link' => $socials->getVimeo(),
        'title' => __('View more on our %1 page', 'Vimeo')
    ]);
}

if (!count($socialsList)) {
    return '';
}
?>

<div class="socials pr-4 lg:w-1/4 md:w-1/2">
    <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">
        <?= $escaper->escapeHtml(__('Socials')); ?>
    </h2>
    <div class="flex flex-wrap gap-4 mt-4">
        <?php foreach ($socialsList as $social): ?>
            <a
                class="hover:scale-90 focus:scale-90 transition-transform"
                href="<?= $escaper->escapeHtml($social['link']); ?>"
                target="_blank"
                rel="noopener noreferrer"
                title="<?= $escaper->escapeHtml($social['title']); ?>"
            >
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor">
                    <use href="<?= $block->getViewFileUrl('Siteation_StoreInfo::images/socials.svg'); ?>#<?= $social['type']; ?>" />
                </svg>
            </a>
        <?php endforeach; ?>
    </div>
</div>
