<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfoNotice;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoNotice $storeInfoNotice */
$storeInfoNotice = $block->getStoreInfoNotice();

$classes = implode(' ', array_filter([
    'message global note',
    $block->getCssClasses()
]));
?>

<?php if ($message = $storeInfoNotice->getNotices()): ?>
    <section
        class="<?= $escaper->escapeHtmlAttr($classes) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Store Notice')) ?>"
    >
        <div class="container">
            <p><?= $escaper->escapeHtml($message, ['a', 'strong', 'em', 'br']); ?></p>
        </div>
    </section>
<?php endif; ?>
