<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfoSocials;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoSocials $storeInfoSocials */
$storeInfoSocials = $block->getStoreInfoSocials();
$socialsList = $storeInfoSocials->getList();

$classes = $block->getCssClasses() ?: 'storeinfo';

$headingTag = $block->getHeadingTag() ?? 'h2';
$headingText = $block->getHeading();
$headingClasses = $block->getHeadingCssClasses() ?? 'mb-4 text-md leading-5 font-semibold tracking-wider uppercase';

$iconSize = $block->getIconSize() ?: 32;
$iconColor = $block->getIconColor() ?: 'currentColor';
?>

<?php if ($socialsList): ?>
    <div class="<?= $escaper->escapeHtmlAttr($classes) ?>">
        <?php if($headingText): ?>
            <<?= $escaper->escapeHtmlAttr($headingTag) ?>
                class="title <?= $escaper->escapeHtmlAttr($headingClasses) ?>"
            >
                <?= $escaper->escapeHtml($headingText); ?>
            </<?= $escaper->escapeHtmlAttr($headingTag) ?>>
        <?php endif; ?>
        <div class="socials inline-flex flex-wrap gap-4">
            <?php foreach ($socialsList as $social): ?>
                <a
                    class="hover:scale-90 focus:scale-90 transition-transform text-primary"
                    href="<?= $escaper->escapeHtml($social['link']); ?>"
                    target="_blank"
                    rel="noopener noreferrer"
                    title="<?= $escaper->escapeHtml(__('Go to our %1 page', $social['title'])); ?>"
                >
                    <svg
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                        width="<?= $escaper->escapeHtmlAttr($iconSize) ?>"
                        height="<?= $escaper->escapeHtmlAttr($iconSize) ?>"
                        fill="<?= $escaper->escapeHtmlAttr($iconColor) ?>"
                    >
                        <use href="<?= $block->getViewFileUrl('Siteation_StoreInfo::images/socials.svg'); ?>#<?= $social['type']; ?>" />
                    </svg>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
